services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes: 
      - db_database_wp:/var/lib/mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=escuderodev
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1403
    expose: 
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=1403
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_database_wp: 
  wordpress_data:

# executar com o comando docker compose -f wordpress.yml up
# parar o server com Ctrl + C